/**
 * exercises.ts — Banco de ejercicios completo (Protocol Zero + Gym)
 * Incluye calistenia, combate, ruck y ejercicios de gym para Fase 4
 * Dependencias: workout.types
 */

import type { Ejercicio } from '@/types/workout.types';

export const EXERCISES: Ejercicio[] = [
  // ─── CALISTENIA — EMPUJE ───
  {
    id: 'flexiones-standard',
    nombre: 'Flexiones',
    grupo_muscular: 'EMPUJE',
    tipo: 'CALISTENIA',
    requiere: [],
    variante_casa: null,
    exercise_db_id: '0662',
    notas_tecnica: 'Cuerpo recto, codos a 45°, pecho toca el suelo',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'flexiones-diamante',
    nombre: 'Flexiones diamante',
    grupo_muscular: 'EMPUJE',
    tipo: 'CALISTENIA',
    requiere: [],
    variante_casa: null,
    exercise_db_id: '0638',
    notas_tecnica: 'Manos juntas formando diamante, codos pegados al cuerpo',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'flexiones-declinadas',
    nombre: 'Flexiones declinadas',
    grupo_muscular: 'EMPUJE',
    tipo: 'CALISTENIA',
    requiere: ['banco/silla'],
    variante_casa: null,
    exercise_db_id: '0639',
    notas_tecnica: 'Pies elevados a 40-50cm, mayor énfasis en hombros y pecho superior',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'dips',
    nombre: 'Fondos en paralelas',
    grupo_muscular: 'EMPUJE',
    tipo: 'CALISTENIA',
    requiere: ['paralelas/sillas'],
    variante_casa: null,
    exercise_db_id: '0627',
    notas_tecnica: 'Inclinar torso adelante para pecho, recto para tríceps',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'pike-pushup',
    nombre: 'Pike push-ups',
    grupo_muscular: 'EMPUJE',
    tipo: 'CALISTENIA',
    requiere: [],
    variante_casa: null,
    exercise_db_id: null,
    notas_tecnica: 'Cadera alta en V invertida, trabajo de hombros',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  // ─── CALISTENIA — JALE ───
  {
    id: 'dominadas-pronadas',
    nombre: 'Dominadas pronadas',
    grupo_muscular: 'JALE',
    tipo: 'CALISTENIA',
    requiere: ['barra'],
    variante_casa: null,
    exercise_db_id: '0651',
    notas_tecnica: 'Agarre prono ancho, mentón pasa la barra, bajar controlado',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'dominadas-supinas',
    nombre: 'Dominadas supinas (chin-ups)',
    grupo_muscular: 'JALE',
    tipo: 'CALISTENIA',
    requiere: ['barra'],
    variante_casa: null,
    exercise_db_id: '0253',
    notas_tecnica: 'Agarre supino a la anchura de hombros, énfasis en bíceps',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'australian-pullup',
    nombre: 'Remo invertido (australian)',
    grupo_muscular: 'JALE',
    tipo: 'CALISTENIA',
    requiere: ['barra baja/mesa'],
    variante_casa: null,
    exercise_db_id: null,
    notas_tecnica: 'Cuerpo recto debajo de barra baja, tirar pecho a la barra',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  // ─── CALISTENIA — PIERNAS ───
  {
    id: 'sentadilla-calistenia',
    nombre: 'Sentadillas',
    grupo_muscular: 'PIERNAS',
    tipo: 'CALISTENIA',
    requiere: [],
    variante_casa: null,
    exercise_db_id: '0043',
    notas_tecnica: 'Romper paralelo, peso en talones, rodillas hacia afuera',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'mochila-squat',
    nombre: 'Sentadillas con mochila lastrada',
    grupo_muscular: 'PIERNAS',
    tipo: 'CALISTENIA',
    requiere: ['mochila'],
    variante_casa: null,
    exercise_db_id: null,
    notas_tecnica: 'Mochila con peso al frente del pecho o en la espalda',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'pistol-squat',
    nombre: 'Pistol squat',
    grupo_muscular: 'PIERNAS',
    tipo: 'CALISTENIA',
    requiere: [],
    variante_casa: null,
    exercise_db_id: '1489',
    notas_tecnica: 'Una pierna, bajar controlado, usar soporte si es necesario',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'sentadilla-bulgara',
    nombre: 'Sentadilla búlgara',
    grupo_muscular: 'PIERNAS',
    tipo: 'CALISTENIA',
    requiere: ['banco/silla'],
    variante_casa: null,
    exercise_db_id: '1757',
    notas_tecnica: 'Pie trasero elevado, rodilla delantera no pasa la punta del pie',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'lunges',
    nombre: 'Zancadas',
    grupo_muscular: 'PIERNAS',
    tipo: 'CALISTENIA',
    requiere: [],
    variante_casa: null,
    exercise_db_id: '0333',
    notas_tecnica: 'Paso largo, rodilla trasera casi toca el suelo',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'calf-raises',
    nombre: 'Elevación de talones',
    grupo_muscular: 'PIERNAS',
    tipo: 'CALISTENIA',
    requiere: [],
    variante_casa: null,
    exercise_db_id: '1373',
    notas_tecnica: 'En escalón para rango completo, pausa arriba 2 seg',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  // ─── CALISTENIA — CORE ───
  {
    id: 'plancha',
    nombre: 'Plancha',
    grupo_muscular: 'CORE',
    tipo: 'CALISTENIA',
    requiere: [],
    variante_casa: null,
    exercise_db_id: '0539',
    notas_tecnica: 'Cuerpo recto, glúteos y core apretados, no hundir cadera',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'plancha-lateral',
    nombre: 'Plancha lateral',
    grupo_muscular: 'CORE',
    tipo: 'CALISTENIA',
    requiere: [],
    variante_casa: null,
    exercise_db_id: null,
    notas_tecnica: 'De costado, cadera alta, oblicuos activados',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'hollow-body',
    nombre: 'Hollow body hold',
    grupo_muscular: 'CORE',
    tipo: 'CALISTENIA',
    requiere: [],
    variante_casa: null,
    exercise_db_id: null,
    notas_tecnica: 'Espalda baja pegada al suelo, brazos y piernas extendidos',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'leg-raises',
    nombre: 'Elevación de piernas',
    grupo_muscular: 'CORE',
    tipo: 'CALISTENIA',
    requiere: ['barra'],
    variante_casa: null,
    exercise_db_id: '0472',
    notas_tecnica: 'Colgado de barra, subir piernas rectas hasta 90°',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'mountain-climbers',
    nombre: 'Mountain climbers',
    grupo_muscular: 'CORE',
    tipo: 'CALISTENIA',
    requiere: [],
    variante_casa: null,
    exercise_db_id: '0658',
    notas_tecnica: 'Posición de plancha, rodillas al pecho alternando rápido',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  // ─── COMBATE — MCMAP ───
  {
    id: 'shadow-boxing',
    nombre: 'Shadow boxing',
    grupo_muscular: 'COMBATE',
    tipo: 'COMBATE',
    requiere: [],
    variante_casa: null,
    exercise_db_id: null,
    notas_tecnica: 'Guardia alta, combinaciones jab-cross-hook, movimiento de pies',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'burpees-combate',
    nombre: 'Burpees de combate',
    grupo_muscular: 'COMBATE',
    tipo: 'COMBATE',
    requiere: [],
    variante_casa: null,
    exercise_db_id: null,
    notas_tecnica: 'Burpee + golpe al subir + sprawl al bajar',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'ground-fighting-drills',
    nombre: 'Drills de suelo (Systema)',
    grupo_muscular: 'COMBATE',
    tipo: 'COMBATE',
    requiere: [],
    variante_casa: null,
    exercise_db_id: null,
    notas_tecnica: 'Rolls, levantarse del suelo rápido, movimiento serpiente',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'systema-breathing',
    nombre: 'Respiración Systema + tensión',
    grupo_muscular: 'COMBATE',
    tipo: 'COMBATE',
    requiere: [],
    variante_casa: null,
    exercise_db_id: null,
    notas_tecnica: 'Inhalar nariz, exhalar boca, ciclos de tensión/relajación corporal',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'striking-combinations',
    nombre: 'Combinaciones de golpes',
    grupo_muscular: 'COMBATE',
    tipo: 'COMBATE',
    requiere: [],
    variante_casa: null,
    exercise_db_id: null,
    notas_tecnica: 'Practiar combos: 1-2, 1-2-3, 1-2-5-2, con footwork',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  // ─── CARDIO / RUCK ───
  {
    id: 'ruck-march',
    nombre: 'Ruck march',
    grupo_muscular: 'CARDIO',
    tipo: 'RUCK',
    requiere: ['mochila lastrada'],
    variante_casa: null,
    exercise_db_id: null,
    notas_tecnica: 'Mochila 10-20kg, paso firme, postura erguida, siempre sábado',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'sprint-intervals',
    nombre: 'Sprints intervalados',
    grupo_muscular: 'CARDIO',
    tipo: 'CARDIO',
    requiere: [],
    variante_casa: null,
    exercise_db_id: null,
    notas_tecnica: '30seg sprint / 60seg trote, 8-12 rondas',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  {
    id: 'running',
    nombre: 'Correr',
    grupo_muscular: 'CARDIO',
    tipo: 'CARDIO',
    requiere: [],
    variante_casa: null,
    exercise_db_id: null,
    notas_tecnica: 'Ritmo constante, respiración nasal si es posible',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 0,
  },
  // ─── GYM — MULTIARTICULARES (Fase 4) ───
  {
    id: 'barbell-squat',
    nombre: 'Sentadilla con barra',
    grupo_muscular: 'PIERNAS',
    tipo: 'GYM',
    requiere: ['barra', 'rack'],
    variante_casa: 'mochila-squat',
    exercise_db_id: '0043',
    notas_tecnica: 'Bajá hasta paralelo, rodillas hacia afuera, core firme',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 5,
  },
  {
    id: 'deadlift',
    nombre: 'Peso muerto',
    grupo_muscular: 'PIERNAS',
    tipo: 'GYM',
    requiere: ['barra'],
    variante_casa: 'sentadilla-bulgara',
    exercise_db_id: '0032',
    notas_tecnica: 'Espalda neutra, barra pegada a las piernas, empujá el suelo',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 5,
  },
  {
    id: 'bench-press',
    nombre: 'Press banca',
    grupo_muscular: 'EMPUJE',
    tipo: 'GYM',
    requiere: ['barra', 'banco'],
    variante_casa: 'flexiones-declinadas',
    exercise_db_id: '0025',
    notas_tecnica: 'Escápulas retraídas, arco natural en espalda baja, codos a 45°',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 2.5,
  },
  {
    id: 'overhead-press',
    nombre: 'Press militar',
    grupo_muscular: 'EMPUJE',
    tipo: 'GYM',
    requiere: ['barra'],
    variante_casa: 'pike-pushup',
    exercise_db_id: '0431',
    notas_tecnica: 'De pie, barra desde clavículas, empujar vertical, core apretado',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 2.5,
  },
  {
    id: 'barbell-row',
    nombre: 'Remo con barra',
    grupo_muscular: 'JALE',
    tipo: 'GYM',
    requiere: ['barra'],
    variante_casa: 'australian-pullup',
    exercise_db_id: '0027',
    notas_tecnica: 'Torso a 45°, tirar a la cintura, apretar escápulas arriba',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 2.5,
  },
  {
    id: 'weighted-pullup',
    nombre: 'Dominadas lastradas',
    grupo_muscular: 'JALE',
    tipo: 'GYM',
    requiere: ['barra', 'cinturón/disco'],
    variante_casa: 'dominadas-pronadas',
    exercise_db_id: '0651',
    notas_tecnica: 'Mismo patrón que dominadas normales pero con disco colgando',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 2.5,
  },
  {
    id: 'weighted-dips',
    nombre: 'Fondos lastrados',
    grupo_muscular: 'EMPUJE',
    tipo: 'GYM',
    requiere: ['paralelas', 'cinturón/disco'],
    variante_casa: 'dips',
    exercise_db_id: '0627',
    notas_tecnica: 'Misma técnica que fondos normales, disco colgando de cinturón',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 2.5,
  },
  // ─── GYM — ACCESORIOS ───
  {
    id: 'bicep-curl',
    nombre: 'Curl de bíceps',
    grupo_muscular: 'JALE',
    tipo: 'GYM',
    requiere: ['mancuernas/barra'],
    variante_casa: 'dominadas-supinas',
    exercise_db_id: '0231',
    notas_tecnica: 'Codos fijos, sin balanceo, contracción completa',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 1,
  },
  {
    id: 'tricep-pushdown',
    nombre: 'Extensión de tríceps en polea',
    grupo_muscular: 'EMPUJE',
    tipo: 'GYM',
    requiere: ['polea'],
    variante_casa: 'flexiones-diamante',
    exercise_db_id: '0860',
    notas_tecnica: 'Codos pegados al cuerpo, extensión completa abajo',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 1,
  },
  {
    id: 'lateral-raises',
    nombre: 'Elevaciones laterales',
    grupo_muscular: 'EMPUJE',
    tipo: 'GYM',
    requiere: ['mancuernas'],
    variante_casa: 'pike-pushup',
    exercise_db_id: '0312',
    notas_tecnica: 'Brazos casi estirados, subir hasta horizontal, controlar bajada',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 1,
  },
  {
    id: 'face-pull',
    nombre: 'Face pulls',
    grupo_muscular: 'JALE',
    tipo: 'GYM',
    requiere: ['polea/banda'],
    variante_casa: 'australian-pullup',
    exercise_db_id: null,
    notas_tecnica: 'Polea alta, tirar hacia la cara, rotación externa arriba',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 1,
  },
  {
    id: 'hip-thrust',
    nombre: 'Hip thrust con barra',
    grupo_muscular: 'PIERNAS',
    tipo: 'GYM',
    requiere: ['barra', 'banco'],
    variante_casa: 'sentadilla-bulgara',
    exercise_db_id: '1418',
    notas_tecnica: 'Espalda alta en banco, empujar cadera al techo, apretar glúteos',
    progresion_recomendada: 'LINEAL',
    incremento_kg_por_sesion: 5,
  },
];

export function getExerciseById(id: string): Ejercicio | undefined {
  return EXERCISES.find((e) => e.id === id);
}

export function getExercisesByType(tipo: Ejercicio['tipo']): Ejercicio[] {
  return EXERCISES.filter((e) => e.tipo === tipo);
}

export function getExercisesByGroup(grupo: Ejercicio['grupo_muscular']): Ejercicio[] {
  return EXERCISES.filter((e) => e.grupo_muscular === grupo);
}
